# #print ("Hello" [3])
# #print ("Good Morning"[11] )
# #print ("octucode"[3])
# #print (len ("OctuCode"))
# #print (len (str(12345)) )
# #print (len (str (13748749)))
# #name = input ("Enter your pin number\n")
# #print (len (str(name)))

# #pin_number = input("Enter you passcode : \n")
# #print (len (str(pin_number)))

# #print (type (3))
# #print (type ("3"))
# #print (type (True))
# #user_pin = input ("Enter your pin code :\n")
# #print ( len ((user_pin)))
# #user_pin = input ("Enter your passcode:\n")
# #print (len (str(user_pin)))

# numbers = ("Enter your digits: \n")
# first_number = int(numbers[0])
# second_number = int(numbers[1])
# print(first_number+second_number)

print ("Hello" [1])